// Generated by scripts/cutout-product-images.mjs -- do not edit by hand.
export const productImageSizes: Record<string, readonly [number, number]> = {
  "/media/produkte/atx-package.webp": [
    301,
    222
  ],
  "/media/produkte/atx-pink.webp": [
    523,
    389
  ],
  "/media/produkte/hb4-klingen.webp": [
    331,
    519
  ],
  "/media/produkte/hb4-powerpack.webp": [
    625,
    625
  ],
  "/media/produkte/hb6-klingen.webp": [
    337,
    522
  ],
  "/media/produkte/hb6-powerpack.webp": [
    626,
    626
  ],
  "/media/produkte/headslick-5oz.webp": [
    467,
    467
  ],
  "/media/produkte/moto-detail.webp": [
    473,
    375
  ],
  "/media/produkte/moto-headcase.webp": [
    300,
    322
  ],
  "/media/produkte/moto-package.webp": [
    582,
    582
  ]
};
